### ISSUE TITLE
Funciona no linux ubuntu

### ISSUE THREAD

**Issue by marcelokrol** [Laranjeiras/Zion.NFe.Danfe#6]
Ola boa noite
Primeiramente excelente projeto, obrigado por compartilhar conosco.

Mas a dúvida, ele funciona no net 8, em um servidor linux ubuntu? 
Pelo que vi o seu projeto usa o PdfClown e ele faz uso do netFramwrok 4.6.1

**Comment by laserguimaraes** [comment]
testei no linux e não funcionou para mim.

**Comment by marcelokrol** [comment]
Depois de muito pesquisar e tambem para ganharmos tempo com desenvolvimento, vamos subir uma VPS com windows e rodar um serviço para impressão de DANFE no IIS, pois todos os pacotes necessitam do net framework. Assim que tiver terminado o projeto e com tempo, vamos desenvolver alguma coisa nativa no net 8 para geração do danfe que rode no linux.
Mas mesmo assim obrigado pelo seu retorno
